name: Embed metrics
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  embed-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
